config/routes.rb
Personal2::Application.routes.draw do
match '/projects' => 'pages#projects'
match '/painting' => 'pages#painting'
match '/about'    => 'pages#about'

root :to => 'pages#newindex'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  protect_from_forgery
  layout 'application'
  respond_to :js

  def index
  end
  
  def newindex
  end

  def projects
  end

  def painting
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crashing my browser with an infinite loop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- >
<section class="nav">
<ul>
	<li><%= link_to 'home', 	root_path, 	   class: 'selected', remote: true %></li>
	<li><%= link_to 'laptop',  projects_path, remote: true %></li>
	<li><%= link_to 'paintbrush', painting_path, remote: true %></li>	
	<li><%= link_to 'attitude', 	about_path,    remote: true %></li>
</ul>
</section>
    
    -->

<%= yield %>

</body>
</html>

app/views/pages/_about.html.erb
<section class="title"><a href="#">verdi ergün</a>
</section>
<aside class="content"><%= link_to 'Li', 'http://www.linkedin.com/in/verdiergun' %><br />
<%= link_to 'Fb', 'http://www.facebook.com/vergun' %><br />
<%= mail_to 'M', 'vergun@gmail.com' %></aside>

app/views/pages/_home.html.erb
<section class="title"><a href="#">this site is live</a>
</section>
<aside class="content">The old site is gone. Burn the bridges as they say. What prompted the new site? A cheetah is the world's fastest land animal. Non sequitor. That's how the new site came about: out of the blue. 
<p>I don't know why. I don't know why titles and content highlight yellow when you hover over them, either. Life's mysteries. This may be the first [and last] post.</p>
</aside>

app/views/pages/_painting.html.erb
<section class="title"><a href="#">faces (acrylic on canvas)</a>
</section>
<aside class="content"><%= image_tag 'faces.jpg' %></aside>

app/views/pages/_projects.html.erb
<section class="title"><a href="#">instore</a>
</section>
<aside class="content"><%= link_to 'next generation tools for your business', 'https://instoredoes.com' %></aside>

<section class="title"><a href="#">sword</a>
</section>
<aside class="content"><%= link_to 'dungeon adventure game in ruby', 'http://www.sword.io' %></aside>

<section class="title"><a href="#">ruby console</a>
</section>
<aside class="content"><%= link_to 'A bash emulator built in ruby', 'http://www.github.com/vergun/bash' %></aside>

app/views/pages/about.js.erb
$('.main').html('<%= j render "about" %>')

app/views/pages/index.html.erb
<div class="main"><%= render 'home' %></div>

app/views/pages/index.js.erb
$('.main').html('<%= j render "home" %>')

app/views/pages/newindex.html.erb
<div class="wrapper">
  
  <div class="top-banner"></div>
  <div class="center-image"><%= image_tag 'me.jpg' %><br />
    <ul>
      <li><%= link_to "Github", "http://github.com/vergun", target: "blank" %></li>
      <li><%= link_to "Twitter", "http://twitter.com/vergun", target: "blank" %></li>
    </ul>
  </div>
  <div class="push"></div>
  
</div>

app/views/pages/painting.js.erb
$('.main').html('<%= j render "painting" %>')

app/views/pages/projects.js.erb
$('.main').html('<%= j render "projects" %>')